### ISSUE TITLE
Howto add own debian packages - for example open-vm-tools

### ISSUE THREAD

**Issue by khorsmann** [voiceboys/sbcOS#12]
I am not sure where the hook is to deploy own debian packages like open-vm-tools.
And i asume that i should handle the init-script for starting by-myself as well. Can you point me to the right direction? It could be make switchable via config enviroment or so then.

Build-Maschine:
```
root@sbcbuilder:~/sbcOS/ISO# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
root@sbcbuilder:~/sbcOS/ISO# uname -ra
Linux sbcbuilder 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by adubovikov** [comment]
go to configs add the package to multistrap-bootstrap-debian.conf
next go to base and add the package to install.req
recreate rootfs

**Comment by adubovikov** [comment]
sorry, for "local packages", please go to configs/sbc and add your package to install.req

**Comment by khorsmann** [comment]
Okay this files. I was wondering that base.req didnt shown any file from that package after the build.

SbcOS/configs/multistrap-bootstrap-debian.conf
SbcOS/configs/sbc/install.req

**Comment by adubovikov** [comment]
theoreticaly - not remove the directory - the files will be in cache. I will add the options

**Comment by khorsmann** [comment]
to be sure - after editing this files, i must run "cd SbCOS; bash build_rootfs.sh" and after that, "cd ISO; bash gen_sbc_iso.sh". There are no installed files, so i am a littlebit confused.

 
--

**Comment by khorsmann** [comment]
Could it be, that i allway make an ISO of the same file over and over again?

```
root@sbcbuilder:~/sbcOS/SbcOS#
root@sbcbuilder:~/sbcOS/SbcOS# md5sum /root/sbcOS/SbcOS/build/img/sbc-public.sb
2f77528c8baf4650a94e451361dc85fd  /root/sbcOS/SbcOS/build/img/sbc-public.sb
root@sbcbuilder:~/sbcOS/SbcOS# cd ..
root@sbcbuilder:~/sbcOS# cd ISO/
root@sbcbuilder:~/sbcOS/ISO# ls
gen_sbc_iso.sh  sbc-data
root@sbcbuilder:~/sbcOS/ISO# md5sum sbc-data/
readme.txt  sbc/
root@sbcbuilder:~/sbcOS/ISO# md5sum sbc-data/sbc/
boot/          sbc-public.sb
root@sbcbuilder:~/sbcOS/ISO# md5sum sbc-data/sbc/sbc-public.sb
0b513912d04f603bb395d716534493be  sbc-data/sbc/sbc-public.sb
root@sbcbuilder:~/sbcOS/ISO# ls -lah sbc-data/sbc/sbc-public.sb
-rw-r--r-- 1 root root 89M May 10 13:06 sbc-data/sbc/sbc-public.sb
root@sbcbuilder:~/sbcOS/ISO# cp  /root/sbcOS/SbcOS/build/img/sbc-public.sb
gen_sbc_iso.sh  sbc-data/
root@sbcbuilder:~/sbcOS/ISO# cp  /root/sbcOS/SbcOS/build/img/sbc-public.sb sbc-data/
readme.txt  sbc/
root@sbcbuilder:~/sbcOS/ISO# cp  /root/sbcOS/SbcOS/build/img/sbc-public.sb sbc-data/sbc/
boot/          sbc-public.sb
root@sbcbuilder:~/sbcOS/ISO# cp  /root/sbcOS/SbcOS/build/img/sbc-public.sb sbc-data/sbc/
root@sbcbuilder:~/sbcOS/ISO# bash gen_sbc_iso.sh
I: -input-charset not specified, using utf-8 (detected in locale settings)
```

**Comment by adubovikov** [comment]
no no, if you generated the new rootfs, just copy the file "sbc-public.sb" from SbcOS/build/img/ to ISO/sbc-data/sbc

you do something manual, because to generate an ISO from your manual installation, you should run build script and you will find everything in the /tmp directory. Please read README.md

**Comment by khorsmann** [comment]
Your number one beta tester is right here to follow the instructions. :)

**Comment by adubovikov** [comment]
:-)

**Comment by adubovikov** [comment]
the directory ISO is only for guys who dont want to build it. Probably need move it to somethere else ;-)

**Comment by khorsmann** [comment]
Hmmm. Thats strange. If i follow the steps with "build_rootfs.sh", then copy the "sbc-public.sb" to ISO/sbc-data/sbc/ and then run "build" and afterwards the "/tmp/gen_sbc_iso.sh" files, the ISO boots. But there are no startet processes at all. Only local login is possible.

**Comment by khorsmann** [comment]
Okay it seems to be broken if i try to build vanilla SBC-OS on UBUNTU with the three steps. 

And it seems to be that debian is the "main SBC-OS" - maybe i should try that and drop UBUNTU.

Build the rootfs, copy the sbc-public.sb to the right place for the ISO and run the main build script. Afterwards run the temp-build files results in an booting SBC-OS without mount-points, no network, no processes.

```
root@sbcbuilder:~/sbcOS# cp /tmp/sbc-x86_64.zip /vagrant/
root@sbcbuilder:~/sbcOS# find -iname sbc-public.sb | xargs md5sum
04a7648a6ad3f73bc024a87da1f5e0c7  ./ISO/sbc-data/sbc/sbc-public.sb
04a7648a6ad3f73bc024a87da1f5e0c7  ./SbcOS/build/img/sbc-public.sb
```

**Comment by adubovikov** [comment]
no, no... I have build without any problem under Ubuntu 18. Did you use 18 ?

**Comment by adubovikov** [comment]
just pushed the update to run everyting only using the build script in the root
can you please try ?

**Comment by khorsmann** [comment]
I updated the description for the Ubuntu build Maschine in the first comment.

I will try it with the Ubuntu Maschine and report then

**Comment by khorsmann** [comment]
@adubovikov Alex, so i only use build? Must i change the config File to "UBUNTU=true" then, i guess?


```
root@sbcbuilder:~/sbcOS# bash build
Changing current directory to /root/sbcOS
Building intramfs image...
Module xt_RTPENGINE.ko doesnt exists try to compile first
make -C /lib/modules/4.15.0-48-generic/build M=/root/sbcOS/initramfs/source/rtpengine-mr7.1.1.1/kernel-module O=/lib/modules/4.15.0-48-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-48-generic'
make[2]: Entering directory '/usr/src/linux-headers-4.15.0-48-generic'
/usr/src/linux-headers-4.15.0-48-generic/Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /root/sbcOS/initramfs/source/rtpengine-mr7.1.1.1/kernel-module/xt_RTPENGINE.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/sbcOS/initramfs/source/rtpengine-mr7.1.1.1/kernel-module/xt_RTPENGINE.mod.o
  LD [M]  /root/sbcOS/initramfs/source/rtpengine-mr7.1.1.1/kernel-module/xt_RTPENGINE.ko
make[2]: Leaving directory '/usr/src/linux-headers-4.15.0-48-generic'
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-48-generic'
Module xt_RTPENGINE.ko has been compiled! Copying...
/tmp/sbc-initramfs-1929.img
-----------------------------
Finished. Find your result in /tmp/sbc-data-1918
To build ISO, run: /tmp/gen_sbc_iso.sh
To build ZIP, run: /tmp/gen_sbc_zip.sh
```

```
root@sbcbuilder:~/sbcOS# find . -type f -iname sbc-public.sb | xargs md5sum
3eca1b1b5c4cfff53fb5f49d17e94f5b  ./ISO/sbc-data/sbc/sbc-public.sb
04a7648a6ad3f73bc024a87da1f5e0c7  ./SbcOS/build/img/sbc-public.sb
root@sbcbuilder:~/sbcOS# find /tmp/ -type f -iname sbc-public.sb | xargs m5sum
xargs: m5sum: No such file or directory
root@sbcbuilder:~/sbcOS# find /tmp/ -type f -iname sbc-public.sb
/tmp/sbc-data-1918/sbc/sbc-public.sb
root@sbcbuilder:~/sbcOS# find /tmp/ -type f -iname sbc-public.sb | xargs md5sum
04a7648a6ad3f73bc024a87da1f5e0c7  /tmp/sbc-data-1918/sbc/sbc-public.sb
```

**Comment by khorsmann** [comment]
Okay - build it without any change on the config and then i executed the /tmp/gen_sbc_iso.sh. And its broken afterwards.

**Comment by adubovikov** [comment]
so, after you executed /tmp/gen_sbc_iso.sh did you see sbc-x86_64.iso in the /tmp ?

**Comment by adubovikov** [comment]
so, this iso you can start with ? 
qemu-system-x86_64 -boot d -cdrom /tmp/sbc_public_x86_64.iso  -m 512

**Comment by khorsmann** [comment]
To my shame i am on windows 10 with virtualbox / vagrant for "building" and copy that ISO to /vagrant/ so  its reachable for Windows again. Then i start another virtualbox that boots from this ISO.
WIth the rootfs that is already shipped in /ISO/ folder, it works this way.

**Comment by adubovikov** [comment]
sorry, i confuse :-) what doesnt work right now ? The rootfs that you have build by self ?

**Comment by khorsmann** [comment]
Oh okay. Indeed its not clear what "iso" i mean.

*WORKS* /sbcOS/ISO/gen_sbc_iso.sh generated ISO (let as named this "the vendor shipped version")

*BROKEN* bash build ;  bash /tmp/gen_sbc_iso.sh

btw - broken for me on UBUNTU and DEBIAN.

**Comment by adubovikov** [comment]
ok, can you please do on the host there you run the build script do:
uname -r
ls -l /init* 
ls -l /vmlinuz

and show the result here

**Comment by khorsmann** [comment]
Hi Alex,

thank you for investigating.

After so much trouble with the UBUNTU box (description below) i tried also DEBIAN. (first description below). Why i am using vagrant? Cos with the Vagrant File and the public boxen its a littlebit like an poors men *docker* style to reproduce my doing (for my collegues for example). And you can destroy/recreate the VM again and again to get an "clean" enviroment. And i my case, i can report you if i took my laptop with me.

Here the needed Informations:

Debian BUILDER Box:
```
uname -r
4.9.0-9-amd64
ls -l /init*
lrwxrwxrwx 1 root root 29 Apr 30 20:00 /initrd.img -> boot/initrd.img-4.9.0-9-amd64
lrwxrwxrwx 1 root root 29 Apr 30 19:56 /initrd.img.old -> boot/initrd.img-4.9.0-6-amd64
ls -l /vmlinuz
lrwxrwxrwx 1 root root 26 Apr 30 20:00 /vmlinuz -> boot/vmlinuz-4.9.0-9-amd64
lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

Ubuntu BUILDER Box
```
uname -r
4.15.0-48-generic
ls -l /init*
lrwxrwxrwx 1 root root 33 May  8 15:50 /initrd.img -> boot/initrd.img-4.15.0-48-generic
lrwxrwxrwx 1 root root 33 May  8 15:50 /initrd.img.old -> boot/initrd.img-4.15.0-48-generic
ls -l /vmlinuz
lrwxrwxrwx 1 root root 30 May  8 15:50 /vmlinuz -> boot/vmlinuz-4.15.0-48-generic
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

My Vagrant File to see the source of the images. I run also apt-get update / upgrade on the boxes.
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  config.vm.define "builder-debian", autostart: true do |subconfig|
    # subconfig.vm.box = "ubuntu/bionic64"
    subconfig.vm.box = "debian/stretch64"
    subconfig.vm.hostname = "sbcbuilder"
    subconfig.vm.synced_folder ".", "/vagrant", type: 'virtualbox',
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=755,fmode=644"]
    subconfig.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
    end
    
  end

  config.vm.define "builder-ubuntu", autostart: false do |subconfig|
    subconfig.vm.box = "ubuntu/bionic64"
    subconfig.vm.hostname = "sbcbuilder"
    subconfig.vm.synced_folder ".", "/vagrant", type: 'virtualbox',
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=755,fmode=644"]
    subconfig.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
    end
    
  end

# apt-get update
# apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 40976EAF437D05B5
# apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 8B48AD6246925553
# apt-get install whois dirmngr multistrap reprepro binutils squashfs-tools genisoimage make linux-headers-$(uname -r)
# apt-get install genisoimage whois git zip

end
```

**Comment by adubovikov** [comment]
Karsten, for me looks all good, can you somehow share to me the sbc-public.sb that you has been generated from "build_rootfs.sh" script ? I will check what is going wrong and give you feedback asap

**Comment by khorsmann** [comment]
Hi Alex,

sure i uploaded the image to my webserver. I will send you via Email (to your gmail account) the link to it.

**Comment by adubovikov** [comment]
Just checked, upload the .sb to my ISO - all works perfect.
Can you please send your directory /tmp/sbc-data-XXX exclude .sb to me?
![Screenshot from 2019-05-11 15-51-47](https://user-images.githubusercontent.com/4513061/57570658-b660d000-7404-11e9-8a39-f3f0d734c7d1.png)

**Comment by khorsmann** [comment]
Mdsum looks good. 

I will do that this evening and email you the details. Any other logfiles? 

Cos that lives in the /tmp folder and I shutdown the Maschine all stuff for this build is lost.

**Comment by adubovikov** [comment]
ok, i will fix it to make build all stuff in the build directory of sbcOS, looks like the best way keep it in once place

**Comment by khorsmann** [comment]
I am fine with /tmp cos that's an clean startup then and after reboot you have maybe no side effects on broken tries (for example missing build host dependcies). 

An sha5sum or whatever of the used sb in the motd would be handy that you can see "ah that's the old one or the new one"

**Comment by khorsmann** [comment]
I send you right now an new bundle of my broken files.

**Comment by khorsmann** [comment]
Hi @adubovikov ,

i found the error. Its an HOST dependencie that is not in the documentation.
The kernel module dkms/aufs.ko is missing. All will be build but ends in a broken ISO image.

With *apt-get install aufs-dkms aufs-tools aufs-dev* it works.

```
root@sbcbuilder:~/check# diff -Nur ORG-NAMES OWN-NAMES
--- ORG-NAMES   2019-06-02 16:36:27.217006023 +0000
+++ OWN-NAMES   2019-06-02 16:36:49.444114003 +0000
@@ -7,7 +7,6 @@
 output/lib/modules/4.9.0-9-amd64/modules.dep
 output/lib/modules/4.9.0-9-amd64/modules.alias.bin
 output/lib/modules/4.9.0-9-amd64/modules.dep.bin
-output/lib/modules/4.9.0-9-amd64/updates/dkms/aufs.ko
 output/lib/modules/4.9.0-9-amd64/modules.builtin.bin
 output/lib/modules/4.9.0-9-amd64/kernel/fs/jbd2/jbd2.ko
 output/lib/modules/4.9.0-9-amd64/kernel/fs/isofs/isofs.ko
```

```
root@sbcbuilder:~/check# apt-cache search aufs
aufs-dev - Development files for aufs
aufs-dkms - DKMS files to build and install aufs
aufs-tools - Tools to manage aufs filesystems
```
