### ISSUE TITLE
Howto "install" the ISO to an hdd or usb-stick?

### ISSUE THREAD

**Issue by khorsmann** [voiceboys/sbcOS#14]
At the moment i do many testing on my local maschine in virtualbox. So there is it easy to run the ISO file to take a look at SBC-OS.

For an testing-lab i want to setup something on my VMWare ESX Host to attach an Test SIP-Core and Test SIPTRUNK. For this purpose it would make sense for me to "install" maybe from the ISO the files on hdd.

Are there any hints to do this easy? I dont want to make VMIMAGES. IPXE would be also an option, cos PXE is default on without OS Installation in VMWARE.

I ask for the "USB-STICK" as well, cos i thought, thats the only installation with permanent storing of configuration changes.

**Comment by adubovikov** [comment]
so, you should run ./build_rootfs.sh in the sbcOS
second, please go to root directory and run ./build
after you will have in the /tmp/ directory sbc-data-XXX

mount your USB stick to /mnt/usb and be sure you have ext4 partition - copy everything from /tmp/sbc-data-XXX to the slice.

after go to the /mnt/usb/sbc/boot and execute ./bootinst.sh

after this your USB stick is bootable...

**Comment by khorsmann** [comment]
I tried that with the shipped ISO - works fine. 
Must use an other Live-ISO cos of lacking the mkfs.ext4 on SBC-OS but thats okay.

One Question "installed" SBC-OS version. How to sync  the changes to the /change/ folder? 
I thought i remember that the ISO Version dont support that, so the copied ISO is then also not capable of it.

**Comment by khorsmann** [comment]
The Question is solved here (how to add the ISO or USB-THUMB-Stick to and hdd)
