### ISSUE TITLE
build on Ubuntu 18.04.3 LTS is not working

### ISSUE THREAD

**Issue by hansju** [voiceboys/sbcOS#24]
I try to generate the ISO on an fresh Ubuntu 18.04.3 LTS. But it is not working.

First problem the location of the gpg file has change. 
Second the KEYS of the installation packets are not available

<---- log of build_rootfs.sh ---->
Last login: Wed Oct  9 12:40:39 2019 from 192.168.100.29
sysadmin@sbcoscreator:~$ uname -a
Linux sbcoscreator 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
sysadmin@sbcoscreator:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
sysadmin@sbcoscreator:~$ pwd
/home/sysadmin
sysadmin@sbcoscreator:~$ cd sbcos/

sysadmin@sbcoscreator:~/sbcos$ git clone https://github.com/voiceboys/sbcOS.git
Cloning into 'sbcOS'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 922 (delta 21), reused 1 (delta 0), pack-reused 875
Receiving objects: 100% (922/922), 184.40 MiB | 5.32 MiB/s, done.
Resolving deltas: 100% (204/204), done.
sysadmin@sbcoscreator:~/sbcos$ 

sysadmin@sbcoscreator:~/sbcos$ ls
sbcOS
sysadmin@sbcoscreator:~/sbcos$ cd sbcOS/
sysadmin@sbcoscreator:~/sbcos/sbcOS$ ls
bootfiles  bootinfo.txt  build  config  DOC  initramfs  ISO  LICENSE  livekitlib  options.txt  README.md  SbcOS  tools
sysadmin@sbcoscreator:~/sbcos/sbcOS$ cd SbcOS/
sysadmin@sbcoscreator:~/sbcos/sbcOS/SbcOS$ sudo su
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS# ./build_rootfs.sh
-= build stripped base rootfs for future squashfs
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/img"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/tmp"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/log"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb/import"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/squashfs"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/bootstrap"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/src"
use parameter [-debian] for update builder
-= build sbc-repository repository
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/rootfs"
cp: cannot stat '/etc/apt/trusted.gpg': No such file or directory
163 ./build_rootfs.sh
 ! error. exiting now.
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#

root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS# vu build_rootfs.sh
vu: command not found
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS# vi +163 build_rootfs.sh

--->          cp /etc/apt/trusted.gpg.d/* "${BOOTSTRAPDIR}/etc/apt"
   
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS# ./build_rootfs.sh
-= build stripped base rootfs for future squashfs
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/img"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/tmp"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/log"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb/import"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/squashfs"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/bootstrap"
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/src"
use parameter [-debian] for update builder
-= build sbc-repository repository
 | create directory "/home/sysadmin/sbcos/sbcOS/SbcOS/build/rfs/rootfs"
 | install current debian stable to setup package repository
multistrap 2.2.9 benutzt /home/sysadmin/sbcos/sbcOS/SbcOS/configs/multistrap-bootstrap-current.conf
multistrap 2.2.9 benutzt /home/sysadmin/sbcos/sbcOS/SbcOS/configs/multistrap-bootstrap-current.conf
Architektur wird nativ vorgegeben als: amd64
multistrap baut amd64-Multistrap auf Â»amd64Â«
I: Symbolischer Link /home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/lib64 -> /home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/lib wird gesetzt.
Getting package lists: APT_CONFIG=/tmp/multistrap.ixT6Tg apt-get  -o Apt::Architecture=amd64 -o Dir::Etc::TrustedParts=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/etc/apt/trusted.gpg.d -o Dir::Etc::Trusted=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/etc/apt/trusted.gpg -o Apt::Get::AllowUnauthenticated=true -o Apt::Get::Download-Only=true -o Apt::Install-Recommends=false -o Dir=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/ -o Dir::Etc=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/etc/apt/ -o Dir::Etc::Parts=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/etc/apt/apt.conf.d/ -o Dir::Etc::PreferencesParts=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/etc/apt/preferences.d/ -o APT::Default-Release=stretch -o Dir::State=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/var/lib/apt/ -o Dir::State::Status=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/var/lib/dpkg/status -o Dir::Cache=/home/sysadmin/sbcos/sbcOS/SbcOS/build/deb-rfs/bootstrap/var/cache/apt/ update
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Holen:2 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Holen:3 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2.365 B]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg
Paketlisten werden gelesen... Fertig
W: GPG-Fehler: http://cdn-fastly.deb.debian.org/debian stretch Release: Die folgenden Signaturen konnten nicht Ã¼berprÃ¼ft werden, weil ihr Ã¶ffentlicher SchlÃ¼ssel nicht verfÃ¼gbar ist: NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC NO_PUBKEY EF0F382A1A7B6500
E: Das Depot Â»http://httpredir.debian.org/debian stretch ReleaseÂ« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgefÃ¼hrt werden, daher ist es standardmÃ¤Ãig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
Apt-Aktualisierung fehlgeschlagen. RÃ¼ckgabewert: 100
171 ./build_rootfs.sh
 ! error. exiting now.
root@sbcoscreator:/home/sysadmin/sbcos/sbcOS/SbcOS#

</-------->

I downloaded missing keys but I got more errors.

Has anybody successful build and ran ISO with Ubuntu 18.04.03 ?

**Comment by melcon** [comment]
Hi @hansju 

I was trying this on a docker container (ubuntu:bionic):
  
```
apt-get update && apt-get install debian-archive-keyring
ln -sv /usr/share/keyrings/debian-archive-*.gpg /etc/apt/trusted.gpg.d/
```
 then change the `cp /etc/apt/trusted.gpg.d/* "${BOOTSTRAPDIR}/etc/apt"` to `cp -a /etc/apt/trusted.gpg.d "${BOOTSTRAPDIR}/etc/apt"`

**Comment by hansju** [comment]
Hello Melcom,

thank you for your tests. The solution is working well.
